id: 11ef86bc345a477fb9a3efd05a768b7a
initial_creation_type: ocr
source_metadata:
  volumes:
    28ef1bd82b134cd6bb3d1306f1526949:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: དེ་ཁོ་ན་ཉིད་ཕྱག་རྒྱ་ཆེན་པོ་ཡི་གེ་མེད་པའི་མན་ངག།
      total_pages: 1902
      volume_number: 26
